openapi: 3.1.0
info:
  contact:
    email: support@swedenconnect.se
    name: Sweden Connect
    url: https://www.swedenconnect.se
  description: "REST API for managing OpenID Federation entities, policies, modules,\
    \ and trust marks. This API provides endpoints for creating, reading, updating,\
    \ and deleting federation entities, policies, trust anchors, resolvers, trust\
    \ marks, and trust mark subjects."
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: OpenID Federation Entity Registry API
  version: 0.5.10-SNAPSHOT
servers:
  - description: Generated server url
    url: http://localhost:8010
security:
  - bearerAuth: [ ]
    selectedOrgNumber: [ ]
tags:
  - description: CRUD for trust mark subjects
    name: TrustmarkSubjects
  - description: CRUD for metadata policies
    name: Policies
  - description: CRUD for federation modules
    name: Modules
  - description: "CRUD for federation, hosted and subordinate entities"
    name: Entities
paths:
  /registry/v1/trustmark-subjects/{id}:
    delete:
      operationId: deleteTrustmarkSubject
      parameters:
        - explode: false
          in: path
          name: id
          required: true
          schema:
            format: uuid
            type: string
          style: simple
      responses:
        "200":
          description: OK
      summary: Delete trust mark subject
      tags:
        - TrustmarkSubjects
      x-accepts:
        - application/json
    get:
      operationId: getTrustmarkSubject
      parameters:
        - explode: false
          in: path
          name: id
          required: true
          schema:
            format: uuid
            type: string
          style: simple
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/TrustmarkSubject'
          description: OK
      summary: Get trust mark subject
      tags:
        - TrustmarkSubjects
      x-accepts:
        - '*/*'
    post:
      operationId: createTrustmarkSubjectWithId
      parameters:
        - explode: false
          in: path
          name: id
          required: true
          schema:
            format: uuid
            type: string
          style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrustmarkSubjectInput'
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/TrustmarkSubject'
          description: OK
      summary: Create trust mark subject with specified ID
      tags:
        - TrustmarkSubjects
      x-content-type: application/json
      x-accepts:
        - '*/*'
    put:
      operationId: updateTrustmarkSubject
      parameters:
        - explode: false
          in: path
          name: id
          required: true
          schema:
            format: uuid
            type: string
          style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrustmarkSubjectInput'
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/TrustmarkSubject'
          description: OK
      summary: Update trust mark subject
      tags:
        - TrustmarkSubjects
      x-content-type: application/json
      x-accepts:
        - '*/*'
  /registry/v1/policies/{id}:
    delete:
      operationId: deletePolicy
      parameters:
        - explode: false
          in: path
          name: id
          required: true
          schema:
            format: uuid
            type: string
          style: simple
      responses:
        "200":
          description: OK
      summary: Delete policy
      tags:
        - Policies
      x-accepts:
        - application/json
    get:
      operationId: getPolicy
      parameters:
        - explode: false
          in: path
          name: id
          required: true
          schema:
            format: uuid
            type: string
          style: simple
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/PolicyDto'
          description: OK
      summary: Get policy by id
      tags:
        - Policies
      x-accepts:
        - '*/*'
    post:
      operationId: createPolicyWithId
      parameters:
        - explode: false
          in: path
          name: id
          required: true
          schema:
            format: uuid
            type: string
          style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PolicyInput'
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/PolicyDto'
          description: OK
      summary: Create policy with specified ID
      tags:
        - Policies
      x-content-type: application/json
      x-accepts:
        - '*/*'
    put:
      operationId: updatePolicy
      parameters:
        - explode: false
          in: path
          name: id
          required: true
          schema:
            format: uuid
            type: string
          style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PolicyInput'
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/PolicyDto'
          description: OK
      summary: Update policy
      tags:
        - Policies
      x-content-type: application/json
      x-accepts:
        - '*/*'
  /registry/v1/modules/trustmark/{id}:
    delete:
      operationId: deleteTrustmark
      parameters:
        - explode: false
          in: path
          name: id
          required: true
          schema:
            format: uuid
            type: string
          style: simple
      responses:
        "200":
          description: OK
      summary: Delete trust mark
      tags:
        - Modules
      x-accepts:
        - application/json
    get:
      operationId: getTrustmark
      parameters:
        - explode: false
          in: path
          name: id
          required: true
          schema:
            format: uuid
            type: string
          style: simple
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Trustmark'
          description: OK
      summary: Get trust mark
      tags:
        - Modules
      x-accepts:
        - '*/*'
    post:
      operationId: createTrustmarkWithId
      parameters:
        - explode: false
          in: path
          name: id
          required: true
          schema:
            format: uuid
            type: string
          style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrustmarkInput'
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Trustmark'
          description: OK
      summary: Create trust mark with specified ID
      tags:
        - Modules
      x-content-type: application/json
      x-accepts:
        - '*/*'
    put:
      operationId: updateTrustmark
      parameters:
        - explode: false
          in: path
          name: id
          required: true
          schema:
            format: uuid
            type: string
          style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrustmarkInput'
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Trustmark'
          description: OK
      summary: Update trust mark
      tags:
        - Modules
      x-content-type: application/json
      x-accepts:
        - '*/*'
  /registry/v1/modules/trust-anchor/{id}:
    delete:
      operationId: deleteTrustAnchor
      parameters:
        - explode: false
          in: path
          name: id
          required: true
          schema:
            format: uuid
            type: string
          style: simple
      responses:
        "200":
          description: OK
      summary: Delete trust anchor
      tags:
        - Modules
      x-accepts:
        - application/json
    get:
      operationId: getTrustAnchor
      parameters:
        - explode: false
          in: path
          name: id
          required: true
          schema:
            format: uuid
            type: string
          style: simple
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/TrustAnchor'
          description: OK
      summary: Get trust anchor
      tags:
        - Modules
      x-accepts:
        - '*/*'
    post:
      operationId: createTrustAnchorWithId
      parameters:
        - explode: false
          in: path
          name: id
          required: true
          schema:
            format: uuid
            type: string
          style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrustAnchorInput'
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/TrustAnchor'
          description: OK
      summary: Create trust anchor with specified ID
      tags:
        - Modules
      x-content-type: application/json
      x-accepts:
        - '*/*'
    put:
      operationId: updateTrustAnchor
      parameters:
        - explode: false
          in: path
          name: id
          required: true
          schema:
            format: uuid
            type: string
          style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrustAnchorInput'
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/TrustAnchor'
          description: OK
      summary: Update trust anchor
      tags:
        - Modules
      x-content-type: application/json
      x-accepts:
        - '*/*'
  /registry/v1/modules/resolver/{id}:
    delete:
      operationId: deleteResolver
      parameters:
        - explode: false
          in: path
          name: id
          required: true
          schema:
            format: uuid
            type: string
          style: simple
      responses:
        "200":
          description: OK
      summary: Delete resolver
      tags:
        - Modules
      x-accepts:
        - application/json
    get:
      operationId: getResolver
      parameters:
        - explode: false
          in: path
          name: id
          required: true
          schema:
            format: uuid
            type: string
          style: simple
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Resolver'
          description: OK
      summary: Get resolver
      tags:
        - Modules
      x-accepts:
        - '*/*'
    post:
      operationId: createResolverWithId
      parameters:
        - explode: false
          in: path
          name: id
          required: true
          schema:
            format: uuid
            type: string
          style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResolverInput'
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Resolver'
          description: OK
      summary: Create resolver with specified ID
      tags:
        - Modules
      x-content-type: application/json
      x-accepts:
        - '*/*'
    put:
      operationId: updateResolver
      parameters:
        - explode: false
          in: path
          name: id
          required: true
          schema:
            format: uuid
            type: string
          style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResolverInput'
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Resolver'
          description: OK
      summary: Update resolver
      tags:
        - Modules
      x-content-type: application/json
      x-accepts:
        - '*/*'
  /registry/v1/entities/subordinate/{id}:
    delete:
      operationId: deleteSubordinateEntity
      parameters:
        - explode: false
          in: path
          name: id
          required: true
          schema:
            format: uuid
            type: string
          style: simple
      responses:
        "200":
          description: OK
      summary: Delete subordinate entity
      tags:
        - Entities
      x-accepts:
        - application/json
    get:
      operationId: getSubordinateEntity
      parameters:
        - explode: false
          in: path
          name: id
          required: true
          schema:
            format: uuid
            type: string
          style: simple
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/SubordinateEntity'
          description: OK
      summary: Get subordinate entity
      tags:
        - Entities
      x-accepts:
        - '*/*'
    post:
      operationId: createSubordinateEntityWithId
      parameters:
        - explode: false
          in: path
          name: id
          required: true
          schema:
            format: uuid
            type: string
          style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubordinateEntityInput'
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/SubordinateEntity'
          description: OK
      summary: Create subordinate entity with specified ID
      tags:
        - Entities
      x-content-type: application/json
      x-accepts:
        - '*/*'
    put:
      operationId: updateSubordinateEntity
      parameters:
        - explode: false
          in: path
          name: id
          required: true
          schema:
            format: uuid
            type: string
          style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubordinateEntityInput'
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/SubordinateEntity'
          description: OK
      summary: Update subordinate entity
      tags:
        - Entities
      x-content-type: application/json
      x-accepts:
        - '*/*'
  /registry/v1/entities/hosted/{id}:
    delete:
      operationId: deleteHostedEntity
      parameters:
        - explode: false
          in: path
          name: id
          required: true
          schema:
            format: uuid
            type: string
          style: simple
      responses:
        "200":
          description: OK
      summary: Delete hosted entity
      tags:
        - Entities
      x-accepts:
        - application/json
    get:
      operationId: getHostedEntity
      parameters:
        - explode: false
          in: path
          name: id
          required: true
          schema:
            format: uuid
            type: string
          style: simple
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/HostedEntity'
          description: OK
      summary: Get hosted entity
      tags:
        - Entities
      x-accepts:
        - '*/*'
    post:
      operationId: createHostedEntityWithId
      parameters:
        - explode: false
          in: path
          name: id
          required: true
          schema:
            format: uuid
            type: string
          style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HostedEntityInput'
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/HostedEntity'
          description: OK
      summary: Create hosted entity with specified ID
      tags:
        - Entities
      x-content-type: application/json
      x-accepts:
        - '*/*'
    put:
      operationId: updateHostedEntity
      parameters:
        - explode: false
          in: path
          name: id
          required: true
          schema:
            format: uuid
            type: string
          style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HostedEntityInput'
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/HostedEntity'
          description: OK
      summary: Update hosted entity
      tags:
        - Entities
      x-content-type: application/json
      x-accepts:
        - '*/*'
  /registry/v1/entities/federation/{id}:
    delete:
      operationId: deleteFederationEntity
      parameters:
        - explode: false
          in: path
          name: id
          required: true
          schema:
            format: uuid
            type: string
          style: simple
      responses:
        "200":
          description: OK
      summary: Delete federation entity
      tags:
        - Entities
      x-accepts:
        - application/json
    get:
      operationId: getFederationEntity
      parameters:
        - explode: false
          in: path
          name: id
          required: true
          schema:
            format: uuid
            type: string
          style: simple
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/FederationEntity'
          description: OK
      summary: Get federation entity
      tags:
        - Entities
      x-accepts:
        - '*/*'
    post:
      operationId: createFederationEntityWithId
      parameters:
        - explode: false
          in: path
          name: id
          required: true
          schema:
            format: uuid
            type: string
          style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FederationEntityInput'
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/FederationEntity'
          description: OK
      summary: Create federation entity with specified ID
      tags:
        - Entities
      x-content-type: application/json
      x-accepts:
        - '*/*'
    put:
      operationId: updateFederationEntity
      parameters:
        - explode: false
          in: path
          name: id
          required: true
          schema:
            format: uuid
            type: string
          style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FederationEntityInput'
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/FederationEntity'
          description: OK
      summary: Update federation entity
      tags:
        - Entities
      x-content-type: application/json
      x-accepts:
        - '*/*'
  /registry/v1/trustmark-subjects:
    post:
      operationId: createTrustmarkSubject
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrustmarkSubjectInput'
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/TrustmarkSubject'
          description: OK
      summary: Create trust mark subject with auto-generated ID
      tags:
        - TrustmarkSubjects
      x-content-type: application/json
      x-accepts:
        - '*/*'
  /registry/v1/policies:
    get:
      operationId: listPolicies
      responses:
        "200":
          content:
            '*/*':
              schema:
                items:
                  $ref: '#/components/schemas/PolicyDto'
                type: array
          description: OK
      summary: List all policies
      tags:
        - Policies
      x-accepts:
        - '*/*'
    post:
      operationId: createPolicy
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PolicyInput'
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/PolicyDto'
          description: OK
      summary: Create policy with auto-generated ID
      tags:
        - Policies
      x-content-type: application/json
      x-accepts:
        - '*/*'
  /registry/v1/modules/trustmark:
    post:
      operationId: createTrustmark
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrustmarkInput'
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Trustmark'
          description: OK
      summary: Create trust mark with auto-generated ID
      tags:
        - Modules
      x-content-type: application/json
      x-accepts:
        - '*/*'
  /registry/v1/modules/trust-anchor:
    post:
      operationId: createTrustAnchor
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrustAnchorInput'
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/TrustAnchor'
          description: OK
      summary: Create trust anchor with auto-generated ID
      tags:
        - Modules
      x-content-type: application/json
      x-accepts:
        - '*/*'
  /registry/v1/modules/resolver:
    post:
      operationId: createResolver
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResolverInput'
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Resolver'
          description: OK
      summary: Create resolver with auto-generated ID
      tags:
        - Modules
      x-content-type: application/json
      x-accepts:
        - '*/*'
  /registry/v1/entities/subordinate:
    post:
      operationId: createSubordinateEntity
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubordinateEntityInput'
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/SubordinateEntity'
          description: OK
      summary: Create subordinate entity with auto-generated ID
      tags:
        - Entities
      x-content-type: application/json
      x-accepts:
        - '*/*'
  /registry/v1/entities/hosted:
    post:
      operationId: createHostedEntity
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HostedEntityInput'
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/HostedEntity'
          description: OK
      summary: Create hosted entity with auto-generated ID
      tags:
        - Entities
      x-content-type: application/json
      x-accepts:
        - '*/*'
  /registry/v1/entities/federation:
    post:
      operationId: createFederationEntity
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FederationEntityInput'
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/FederationEntity'
          description: OK
      summary: Create federation entity with auto-generated ID
      tags:
        - Entities
      x-content-type: application/json
      x-accepts:
        - '*/*'
  /api/v1/federationservice/submodules:
    get:
      operationId: submoduleRecord
      parameters:
        - explode: true
          in: query
          name: instanceid
          required: true
          schema:
            format: uuid
            type: string
          style: form
        - explode: true
          in: query
          name: plain
          required: false
          schema:
            default: false
            type: boolean
          style: form
      responses:
        "200":
          content:
            application/jwt:
              schema:
                type: string
          description: OK
      tags:
        - oidf-service-api-controller
      x-accepts:
        - application/jwt
  /api/v1/federationservice/entity_record:
    get:
      operationId: entityRecord
      parameters:
        - explode: true
          in: query
          name: instanceid
          required: true
          schema:
            format: uuid
            type: string
          style: form
        - explode: true
          in: query
          name: plain
          required: false
          schema:
            default: false
            type: boolean
          style: form
      responses:
        "200":
          content:
            application/jwt:
              schema:
                type: string
          description: OK
      tags:
        - oidf-service-api-controller
      x-accepts:
        - application/jwt
components:
  schemas:
    TrustmarkSubjectInput:
      example:
        trustmarkId: trustmarkId
        expires: expires
        subject: subject
        revoked: true
        granted: granted
      properties:
        trustmarkId:
          description: Trust mark identifier (entity id)
          type: string
        subject:
          description: Subject entity id
          type: string
        revoked:
          description: If the trust mark is revoked for this subject
          type: boolean
        granted:
          description: "Granted time (ISO-8601, e.g. 2025-01-01T00:00:00Z)"
          type: string
        expires:
          description: Expires time (ISO-8601)
          type: string
    TrustmarkSubject:
      example:
        trustmarkId: trustmarkId
        expires: 2000-01-23T04:56:07.000+00:00
        trustmarksubjectId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        subject: subject
        revoked: true
        granted: 2000-01-23T04:56:07.000+00:00
      properties:
        trustmarksubjectId:
          description: Trustmark subject ID
          format: uuid
          type: string
        trustmarkId:
          description: Trust mark identifier (entity id)
          type: string
        subject:
          description: Subject entity id
          type: string
        revoked:
          description: If the trust mark is revoked for this subject
          type: boolean
        granted:
          description: Granted time
          format: date-time
          type: string
        expires:
          description: Expires time
          format: date-time
          type: string
    PolicyInput:
      example:
        name: Default OIDC RP policy
        policy:
          key: ""
      properties:
        name:
          description: Policy name
          example: Default OIDC RP policy
          type: string
        policy:
          additionalProperties: { }
          description: JSON policy document
    PolicyDto:
      example:
        policyId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        name: name
        policy:
          key: ""
      properties:
        policyId:
          format: uuid
          type: string
        name:
          type: string
        policy:
          additionalProperties: { }
    TrustmarkInput:
      example:
        trustMarkEntityId: trustMarkEntityId
        logoUri: logoUri
        trustmarkissuerId: trustmarkissuerId
        delegation: delegation
        refUri: refUri
      properties:
        trustmarkissuerId:
          description: Trust mark issuer entity identifier
          type: string
        trustMarkEntityId:
          description: Trust mark entity identifier
          type: string
        logoUri:
          description: Logo URI
          type: string
        refUri:
          description: Reference URI
          type: string
        delegation:
          description: Delegation JWT
          type: string
    Trustmark:
      example:
        trustmarkId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        trustMarkEntityId: trustMarkEntityId
        logoUri: logoUri
        trustmarkissuerId: trustmarkissuerId
        delegation: delegation
        refUri: refUri
      properties:
        trustmarkId:
          description: Trustmark ID
          format: uuid
          type: string
        trustmarkissuerId:
          description: Trust mark issuer entity identifier
          type: string
        trustMarkEntityId:
          description: Trust mark entity identifier
          type: string
        logoUri:
          description: Logo URI
          type: string
        refUri:
          description: Reference URI
          type: string
        delegation:
          description: Delegation JWT
          type: string
    TrustAnchorInput:
      example:
        active: true
        entityId: entityId
        trustMarkIssuers:
          - trustMarkIssuers
          - trustMarkIssuers
      properties:
        entityId:
          description: Entity identifier for this trust anchor
          type: string
        active:
          description: If this trust anchor is active
          type: boolean
        trustMarkIssuers:
          description: Entity identifiers for trust mark issuers
          items:
            type: string
          type: array
    TrustAnchor:
      example:
        active: true
        entityId: entityId
        moduleId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        trustMarkIssuers:
          - trustMarkIssuers
          - trustMarkIssuers
      properties:
        moduleId:
          description: Module ID
          format: uuid
          type: string
        entityId:
          description: Entity identifier for this trust anchor
          type: string
        active:
          description: If this trust anchor is active
          type: boolean
        trustMarkIssuers:
          description: Entity identifiers for trust mark issuers
          items:
            type: string
          type: array
    ResolverInput:
      example:
        trustAnchor: trustAnchor
        resolveResponseDuration: resolveResponseDuration
        active: true
        entityId: entityId
        stepRetryDuration: stepRetryDuration
        trustedKeys: trustedKeys
      properties:
        entityId:
          description: Entity identifier for this resolver
          type: string
        active:
          description: If this resolver instance is active
          type: boolean
        resolveResponseDuration:
          description: "Response duration (ISO-8601 duration, e.g. PT1H)"
          type: string
        trustAnchor:
          description: Trust anchor entity identifier
          type: string
        trustedKeys:
          description: Trusted keys as JWKS JSON
          type: string
        stepRetryDuration:
          description: "Step retry duration (ISO-8601 duration, e.g. PT1H)"
          type: string
    Resolver:
      example:
        trustAnchor: trustAnchor
        resolveResponseDuration: resolveResponseDuration
        active: true
        entityId: entityId
        stepRetryDuration: stepRetryDuration
        moduleId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        trustedKeys: trustedKeys
      properties:
        moduleId:
          description: Module ID
          format: uuid
          type: string
        entityId:
          description: Entity identifier for this resolver
          type: string
        active:
          description: If this resolver instance is active
          type: boolean
        resolveResponseDuration:
          description: "Response duration (ISO-8601 duration, e.g. PT1H)"
          type: string
        trustAnchor:
          description: Trust anchor entity identifier
          type: string
        trustedKeys:
          description: Trusted keys as JWKS JSON
          type: string
        stepRetryDuration:
          description: "Step retry duration (ISO-8601 duration, e.g. PT1H)"
          type: string
    SubordinateEntityInput:
      example:
        jwks: jwks
        subject: subject
        issuer: issuer
      properties:
        subject:
          description: Subject (entity identifier)
          type: string
        issuer:
          description: Issuer (entity identifier)
          type: string
        jwks:
          description: JWKS as JSON string
          type: string
    SubordinateEntity:
      example:
        jwks: jwks
        subject: subject
        entityId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        issuer: issuer
      properties:
        entityId:
          description: Entity ID
          format: uuid
          type: string
        subject:
          description: Subject (entity identifier)
          type: string
        issuer:
          description: Issuer (entity identifier)
          type: string
        jwks:
          description: JWKS as JSON string
          type: string
    HostedEntityInput:
      example:
        metadata:
          key: ""
        subject: subject
        issuer: issuer
      properties:
        subject:
          description: Subject (entity identifier)
          type: string
        issuer:
          description: Issuer (entity identifier)
          type: string
        metadata:
          additionalProperties: { }
          description: Metadata for hosted entity
    HostedEntity:
      example:
        metadata:
          key: ""
        subject: subject
        entityId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        issuer: issuer
      properties:
        entityId:
          description: Entity ID
          format: uuid
          type: string
        subject:
          description: Subject (entity identifier)
          type: string
        issuer:
          description: Issuer (entity identifier)
          type: string
        metadata:
          additionalProperties: { }
          description: Metadata for hosted entity
    FederationEntityInput:
      example:
        metadata:
          federation_entity: { }
        subject: https://rp.example.se
        issuer: https://ta.example.se
      properties:
        subject:
          description: Subject (entity identifier)
          example: https://rp.example.se
          type: string
        issuer:
          description: Issuer (entity identifier)
          example: https://ta.example.se
          type: string
        metadata:
          additionalProperties: { }
          description: Federation entity metadata
          example:
            federation_entity: { }
    FederationEntity:
      example:
        metadata:
          federation_entity: { }
        subject: https://rp.example.se
        entityId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        issuer: https://ta.example.se
      properties:
        entityId:
          description: Entity ID
          format: uuid
          type: string
        subject:
          description: Subject (entity identifier)
          example: https://rp.example.se
          type: string
        issuer:
          description: Issuer (entity identifier)
          example: https://ta.example.se
          type: string
        metadata:
          additionalProperties: { }
          description: Federation entity metadata
          example:
            federation_entity: { }
  securitySchemes:
    bearerAuth:
      bearerFormat: JWT
      description: JWT token obtained from authentication endpoint
      scheme: bearer
      type: http
    selectedOrgNumber:
      description: Organization number to use for the request. Enter your organization
        number here.
      in: header
      name: selected-org-number
      type: apiKey

